
[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.lint]
# flake8-builtins (A)
# flake8-bugbear (B)
# flake8-comprehensions (C4)
# pycodestyle errors (E)
# Pyfakes (F)
# flake8-future-annotations (FA)
# isort (I)
# flake8-implicit-str-concat (ISC)
# Perflint (PERF)
# flake8-use-pathlib (PTH)
# Pylint (PL)
# flake8-pyi (PYI)
# flake8-return (RET)
# flake8-bandit (S)
# flake8-simplify (SIM)
# Warning (W)
select = ["A", "B", "C4", "E", "F", "FA", "I", "ISC", "PERF", "PL", "PTH", "PYI", "RET", "S", "SIM", "W"]
# select = ["ALL"]
